version: '3'
services:
  manager:
    build: ./ManagerProject/
    ports:
      - "8080:8080"
    networks:
      - network1
    env_file:
      - .env

  worker1:
    build: ./WorkerProject/
    networks:
      - network1

  worker2:
    build: ./WorkerProject/
    networks:
      - network1

  worker3:
    build: ./WorkerProject/
    networks:
      - network1

networks:
  network1:
    driver: bridge